async () => [
  'Metarhia is a Community and Technology Stack',
  'for Distributed Highload Applications and Data Storage',
  '',
  'Activities:',
  '• Academic fields: Research, Education and Open Lectures',
  '• Open Source Contribution e.g. Node.js, Impress, Metasync, etc.',
  '• Services and Products',
  '',
  'Metarhia provides following services:',
  '• Software Development',
  '• Software Audit, Quality Control and Code Review',
  '• Business Processes Analysis',
  '• Architecture Solutions and Consulting',
  '• Database structure and technical specification',
  '• Project planning: time and cost estimation',
  '• Education, Training, Team building and Recruiting',
  '',
  'Metarhia is a group of IT professionals, located in Kiev (Ukraine)',
  'and working together in software development, internet solutions',
  'and production automation. We are experienced in development and',
  'system integration, ours architects are over 20 years in information',
  'technologies. Ours software developers have practical knowledge in',
  'programming including C, C++, JavaScript, Rust, Go, Swift, Java,',
  'Objective-C, Kotlin, C#, Delphi, Assembler, Python, Haskell, etc.',
  'We provide solutions for Unix/Linux, Windows, OSX, Android, Internet',
  'solutions and Embedded systems.'
];
